-- =====================================================================
-- eOne Integration for Business Central — document exits, derived
-- GENERATED by fabric/generate.js from the AL source. Do not hand-edit:
-- re-run the generator instead, or the schema drifts from the API.
-- Target: Microsoft Fabric Warehouse (reduced T-SQL: varchar not nvarchar,
-- datetime2 not datetimeoffset, no DEFAULT constraints, no table hints, and
-- PRIMARY KEY only through ALTER TABLE, as NONCLUSTERED ... NOT ENFORCED).
-- =====================================================================

-- One row per document that has left the open feed, resolved from the event stream.
--
-- This is what replaces applying exits to _rowState during the load. Nothing is written:
-- the current-state views in bc join to this, so an event that arrives late corrects the
-- document on the next read instead of leaving a row wrong forever. It also means the
-- documentEvents map no longer has to run before the others.
--
-- Join on matchId for a document you have the id of, and on matchNumber otherwise; each
-- is ranked separately, so each returns at most one row. When both match, the higher
-- [sequence] is the later exit.

DROP VIEW IF EXISTS [bcModel].[vw_documentExit];
GO
CREATE VIEW [bcModel].[vw_documentExit] AS
WITH x AS (
    SELECT CAST('salesQuotes' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('salesOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('salesInvoices' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('salesCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('salesBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('salesReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('salesReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'salesDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'salesDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('salesReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('salesShipmentPosted', 'salesInvoicePosted', 'salesCreditMemoPosted', 'salesReturnReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseQuotes' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Quote'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseQuotes' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Order'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseInvoices' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Invoice'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseInvoices' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Credit Memo'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseCreditMemos' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Blanket Order'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseBlanketOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('purchaseReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'purchaseDocumentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Cancelled' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Return Order'
       AND e.[eventType] = 'purchaseDocumentCancelled'
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('purchaseReturnOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('purchaseReceiptPosted', 'purchaseInvoicePosted', 'purchaseCreditMemoPosted', 'purchaseReturnShipmentPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('transferOrders' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Transfer Order'
       AND e.[eventType] = 'transferOrderDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('transferOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Transfer Order'
       AND e.[eventType] = 'transferOrderDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('transferOrders' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[sourceDocumentNumber] AS [matchNumber],
           CAST('Posted' AS varchar(10)) AS [rowState],
           e.[documentNumber] AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[eventType] IN ('transferShipmentPosted', 'transferReceiptPosted')
       AND e.[sourceDocumentNumber] <> ''
       AND e.[sourceDocumentNumber] IS NOT NULL
    UNION ALL
    SELECT CAST('warehouseShipments' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Warehouse Shipment'
       AND e.[eventType] = 'warehouseShipmentDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('warehouseShipments' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Warehouse Shipment'
       AND e.[eventType] = 'warehouseShipmentDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
    UNION ALL
    SELECT CAST('warehouseReceipts' AS varchar(100)) AS [entitySet],
           CAST('id' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           e.[documentId] AS [matchId],
           CAST(NULL AS varchar(20)) AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Warehouse Receipt'
       AND e.[eventType] = 'warehouseReceiptDeleted'
       AND e.[documentId] IS NOT NULL
    UNION ALL
    SELECT CAST('warehouseReceipts' AS varchar(100)) AS [entitySet],
           CAST('number' AS varchar(6)) AS [matchKind],
           e.[bcCompanyId], e.[_environment],
           CAST(NULL AS uniqueidentifier) AS [matchId],
           e.[documentNumber] AS [matchNumber],
           CAST('Deleted' AS varchar(10)) AS [rowState],
           CAST(NULL AS varchar(20)) AS [exitRef],
           e.[occurredAt] AS [exitedAt], e.[sequence]
      FROM [bcRaw].[documentEvents] e
     WHERE e.[documentType] = 'Warehouse Receipt'
       AND e.[eventType] = 'warehouseReceiptDeleted'
       AND e.[documentId] IS NULL
       AND e.[documentNumber] <> ''
),
ranked AS (
    SELECT s.*, ROW_NUMBER() OVER (PARTITION BY s.[entitySet], s.[bcCompanyId],
               COALESCE(s.[_environment], ''), s.[matchKind],
               COALESCE(CAST(s.[matchId] AS varchar(36)), s.[matchNumber])
               ORDER BY s.[sequence] DESC) AS [_r]
      FROM x s
)

SELECT r.[entitySet], r.[bcCompanyId], r.[_environment], r.[matchKind], r.[matchId], r.[matchNumber],
       r.[rowState], r.[exitRef], r.[exitedAt], r.[sequence]
  FROM ranked r
 WHERE r.[_r] = 1;
GO
