-- =====================================================================
-- Load health — derived from the landed rows
-- GENERATED by fabric/generate.js from the AL source. Do not hand-edit:
-- re-run the generator instead, or the schema drifts from the API.
-- Target: Microsoft Fabric Warehouse (reduced T-SQL: varchar not nvarchar,
-- datetime2 not datetimeoffset, no DEFAULT constraints, no table hints, and
-- PRIMARY KEY only through ALTER TABLE, as NONCLUSTERED ... NOT ENFORCED).
-- =====================================================================

-- One row per (entity set x company): how many records, how many versions behind them, how
-- many have exited, when a map last wrote, and how current the source data is. Alert on
-- lastLoadedUtc going stale.
--
-- The expensive failure is not a map that errors - the integration reports that. It is a map
-- that quietly stops while the warehouse keeps answering with last week's numbers.
--
-- It reads bcRaw, NOT the bc views, and that is a deliberate cost decision. Monitoring is the
-- query you run every few minutes, and every bc view resolves versions with a window function
-- and joins the exit view twice - which would make the cheapest question in the warehouse the
-- most expensive one to ask. Here rowCount is COUNT(DISTINCT id), the same number the views
-- would produce, without the partitioned sort.
--
-- versionCount over rowCount is the churn ratio, and the signal that compaction is due.
--
-- exitedRowCount comes from vw_documentExit rather than from _rowState, so it counts exits
-- RECORDED rather than exits applied to a landed row. The two differ by exactly the documents
-- vw_dqEventsWithoutDocument reports, which makes the two views a cross-check on each other.

DROP VIEW IF EXISTS [bcModel].[vw_loadHealth];
GO
CREATE VIEW [bcModel].[vw_loadHealth] AS
SELECT CAST('bankGLEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'bankGLEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[bankGLEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('bankGLEntryLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'bankGLEntryLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[bankGLEntryLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('bins' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'bins' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[bins] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('changeLogEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'changeLogEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[changeLogEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('contactPersons' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'contactPersons' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[contactPersons] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('currencies' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'currencies' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[currencies] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('currencyExchangeRates' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'currencyExchangeRates' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[currencyExchangeRates] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('custLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'custLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[custLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerPaymentApplications' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerPaymentApplications' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerPaymentApplications] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerPayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerPayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerPayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerPostingGroups' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerPostingGroups' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerPostingGroups] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customerRefunds' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customerRefunds' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customerRefunds] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('customers' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'customers' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[customers] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('depositApplications' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'depositApplications' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[depositApplications] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('deposits' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'deposits' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[deposits] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('detailedCustLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'detailedCustLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[detailedCustLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('detailedVendorLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'detailedVendorLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[detailedVendorLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('dimensions' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'dimensions' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[dimensions] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('dimensionSetEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'dimensionSetEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[dimensionSetEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('dimensionSetLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'dimensionSetLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[dimensionSetLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('dimensionValues' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'dimensionValues' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[dimensionValues] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('distributions' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'distributions' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[distributions] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('documentAttachments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'documentAttachments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[documentAttachments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('documentEvents' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'documentEvents' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       CAST(NULL AS datetime2(6)) AS newestSourceChangeUtc
  FROM [bcRaw].[documentEvents] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('employeePaymentApplications' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'employeePaymentApplications' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[employeePaymentApplications] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('employeePayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'employeePayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[employeePayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('employees' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'employees' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[employees] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('expenseLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'expenseLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[expenseLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('expenses' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'expenses' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[expenses] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('fiscalPeriods' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'fiscalPeriods' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[fiscalPeriods] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('genBusinessPostingGroups' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'genBusinessPostingGroups' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[genBusinessPostingGroups] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('generalLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'generalLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[generalLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('genProductPostingGroups' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'genProductPostingGroups' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[genProductPostingGroups] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('glAccounts' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'glAccounts' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[glAccounts] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('inventoryAdjustmentLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'inventoryAdjustmentLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[inventoryAdjustmentLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('inventoryAdjustments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'inventoryAdjustments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[inventoryAdjustments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('inventoryPostingGroups' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'inventoryPostingGroups' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[inventoryPostingGroups] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemAttributes' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemAttributes' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemAttributes] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemInventoryAvailabilities' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('snapshot' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemInventoryAvailabilities' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemInventoryAvailabilities] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemReferences' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemReferences' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemReferences] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('items' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'items' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[items] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemTrackingLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemTrackingLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemTrackingLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('itemUnitsOfMeasure' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'itemUnitsOfMeasure' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[itemUnitsOfMeasure] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('journalLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'journalLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[journalLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('journals' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'journals' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[journals] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('locations' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'locations' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[locations] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('notes' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'notes' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[notes] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('paymentMethods' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'paymentMethods' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[paymentMethods] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('paymentTerms' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'paymentTerms' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[paymentTerms] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedCustomerCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedCustomerCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedCustomerCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedCustomerInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedCustomerInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedCustomerInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedCustomerPayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedCustomerPayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedCustomerPayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedCustomerRefunds' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedCustomerRefunds' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedCustomerRefunds] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedDocApplications' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedDocApplications' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       CAST(NULL AS datetime2(6)) AS newestSourceChangeUtc
  FROM [bcRaw].[postedDocApplications] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedEmployeePayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedEmployeePayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedEmployeePayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedPurchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedPurchaseCreditMemoLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedPurchaseCreditMemoLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedPurchaseCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedPurchaseCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedPurchaseCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedPurchaseInvoiceLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedPurchaseInvoiceLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedPurchaseInvoiceLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedPurchaseInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedPurchaseInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedPurchaseInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedPurchaseInvoiceTrackingLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedPurchaseInvoiceTrackingLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedPurchaseInvoiceTrackingLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedSalesCreditMemoLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedSalesCreditMemoLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedSalesCreditMemoLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedSalesCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedSalesCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedSalesCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedSalesInvoiceLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedSalesInvoiceLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedSalesInvoiceLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedSalesInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedSalesInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedSalesInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedSalesInvoiceTrackingLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedSalesInvoiceTrackingLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedSalesInvoiceTrackingLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedVendorCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedVendorCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedVendorCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedVendorInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedVendorInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedVendorInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedVendorPayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedVendorPayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedVendorPayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('postedVendorRefunds' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'postedVendorRefunds' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[postedVendorRefunds] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('priceListHeaders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'priceListHeaders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[priceListHeaders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('priceListLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'priceListLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[priceListLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('processedDocuments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'processedDocuments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[processedDocuments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseBlanketOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseBlanketOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseBlanketOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseBlanketOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseBlanketOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseBlanketOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseCreditMemoLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseCreditMemoLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseInvoiceLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseInvoiceLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseInvoiceLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseQuoteLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseQuoteLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseQuoteLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseQuotes' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseQuotes' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseQuotes] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseReceiptLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseReceiptLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseReceiptLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseReceipts' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseReceipts' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseReceipts] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseReturnOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseReturnOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseReturnOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('purchaseReturnOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'purchaseReturnOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[purchaseReturnOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('returnReceiptLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'returnReceiptLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[returnReceiptLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('returnReceipts' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'returnReceipts' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[returnReceipts] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('returnShipmentLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'returnShipmentLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[returnShipmentLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('returnShipments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'returnShipments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[returnShipments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('routeStops' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'routeStops' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[routeStops] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesBlanketOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesBlanketOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesBlanketOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesBlanketOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesBlanketOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesBlanketOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesCreditMemoLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesCreditMemoLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesCreditMemoLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesInvoiceLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesInvoiceLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesInvoiceLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesLineDiscounts' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesLineDiscounts' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesLineDiscounts] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesperson' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesperson' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesperson] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salespersonPurchasers' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salespersonPurchasers' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salespersonPurchasers] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesPrices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesPrices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesPrices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesQuoteLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesQuoteLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesQuoteLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesQuotes' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesQuotes' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesQuotes] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesReturnOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesReturnOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesReturnOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesReturnOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesReturnOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesReturnOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesShipmentLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesShipmentLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesShipmentLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('salesShipments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('posted' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'salesShipments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[salesShipments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('shipmentMethods' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'shipmentMethods' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[shipmentMethods] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('shippingAgents' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'shippingAgents' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[shippingAgents] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('shippingAgentServices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'shippingAgentServices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[shippingAgentServices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('shipToAddresses' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'shipToAddresses' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[shipToAddresses] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('stockkeepingUnits' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('snapshot' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'stockkeepingUnits' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[stockkeepingUnits] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('transferOrderLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'transferOrderLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[transferOrderLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('transferOrders' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'transferOrders' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[transferOrders] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('unitsOfMeasure' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'unitsOfMeasure' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[unitsOfMeasure] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('valueEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'valueEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[valueEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('variants' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'variants' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[variants] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vatEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vatEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vatEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vatPostingSetup' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vatPostingSetup' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vatPostingSetup] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorCreditMemos' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorCreditMemos' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorCreditMemos] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorInvoices' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorInvoices' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorInvoices] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorLedgerEntries' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('ledger' AS varchar(20)) AS strategy,
       2 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorLedgerEntries' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorLedgerEntries] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorPaymentApplications' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorPaymentApplications' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorPaymentApplications] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorPayments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorPayments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorPayments] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorPostingGroups' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('reference' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorPostingGroups' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorPostingGroups] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendorRefunds' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('staging' AS varchar(20)) AS strategy,
       4 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendorRefunds' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendorRefunds] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('vendors' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('master' AS varchar(20)) AS strategy,
       1 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'vendors' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[vendors] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('warehouseReceiptLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'warehouseReceiptLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[warehouseReceiptLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('warehouseReceipts' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'warehouseReceipts' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[warehouseReceipts] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('warehouseShipmentLines' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'warehouseShipmentLines' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[warehouseShipmentLines] r
 GROUP BY r.[bcCompanyId]
UNION ALL
SELECT CAST('warehouseShipments' AS varchar(100)) AS entitySet,
       CAST('Core' AS varchar(20))  AS appName,
       CAST('open' AS varchar(20)) AS strategy,
       3 AS tier,
       r.[bcCompanyId], MAX(r.[bcCompanyName]) AS companyName,
       COUNT(DISTINCT r.[id]) AS [rowCount],
       COUNT(*) AS versionCount,
       (SELECT COUNT(*) FROM [bcModel].[vw_documentExit] x
         WHERE x.[entitySet] = 'warehouseShipments' AND x.[bcCompanyId] = r.[bcCompanyId]) AS exitedRowCount,
       MAX(r.[_loadedAt]) AS lastLoadedUtc,
       MAX(r.[lastModifiedDateTime]) AS newestSourceChangeUtc
  FROM [bcRaw].[warehouseShipments] r
 GROUP BY r.[bcCompanyId]
;
GO
