-- =====================================================================
-- eOne Integration for Business Central — data quality
-- GENERATED by fabric/generate.js from the AL source. Do not hand-edit:
-- re-run the generator instead, or the schema drifts from the API.
-- Target: Microsoft Fabric Warehouse (reduced T-SQL: varchar not nvarchar,
-- datetime2 not datetimeoffset, no DEFAULT constraints, no table hints, and
-- PRIMARY KEY only through ALTER TABLE, as NONCLUSTERED ... NOT ENFORCED).
-- =====================================================================

-- One row per failing thing. NO ROWS MEANS CLEAN: a check that finds nothing contributes
-- nothing, so there is no "passed" row to read and no check history to maintain.
--
-- vw_loadHealth says whether the maps are running. This says whether what they landed hangs
-- together - the failures that leave every map green and the numbers wrong.
--
-- Each check is its own view, and vw_dataQuality unions them. That split is not cosmetic:
-- these checks scan, and a WHERE checkName = '...' against the union is not guaranteed to
-- skip the other branches' work. Run one view when investigating one thing, and the union
-- on a schedule - not from a dashboard that refreshes.
--
--   vw_dqOrphanLines
--     A line whose header never landed. Usually a header map that failed or is behind its
--     line map; occasionally a header filtered out by a restriction the line map does not
--     share.
--   vw_dqEventsWithoutDocument
--     An exit event for a document that never landed. A document created and gone inside one
--     cycle does this harmlessly; a count that keeps climbing means the document feed is
--     behind, filtered, or not shipped.
--   vw_dqDuplicateKeys
--     One business key under two ids in the same company. BC enforces these keys, so a hit
--     is a load defect - most often rows from two companies landing under one company id.
--   vw_dqDanglingDimSets
--     A row pointing at a dimension set with no entries landed. Dimension reporting silently
--     loses these rows rather than failing.

DROP VIEW IF EXISTS [bcModel].[vw_dqOrphanLines];
GO
-- 16 entity set(s) checked.
CREATE VIEW [bcModel].[vw_dqOrphanLines] AS
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('postedPurchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseCreditMemoLines] l
 WHERE l.[documentNumber] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[postedPurchaseCreditMemos] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[number] = l.[documentNumber])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('postedPurchaseInvoiceLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseInvoiceLines] l
 WHERE l.[documentNumber] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[postedPurchaseInvoices] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[number] = l.[documentNumber])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('postedSalesCreditMemoLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesCreditMemoLines] l
 WHERE l.[documentNumber] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[postedSalesCreditMemos] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[number] = l.[documentNumber])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('postedSalesInvoiceLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesInvoiceLines] l
 WHERE l.[documentNumber] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[postedSalesInvoices] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[number] = l.[documentNumber])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseBlanketOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseBlanketOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseBlanketOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseCreditMemoLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseCreditMemos] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseInvoiceLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseInvoiceLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseInvoices] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseQuoteLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseQuoteLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseQuotes] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('purchaseReturnOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseReturnOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseReturnOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesBlanketOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesBlanketOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesBlanketOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesCreditMemoLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesCreditMemoLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesCreditMemos] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesInvoiceLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesInvoiceLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesInvoices] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesQuoteLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesQuoteLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesQuotes] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId]
UNION ALL
SELECT CAST('orphanLine' AS varchar(16)) AS checkName,
       CAST('salesReturnOrderLines' AS varchar(100)) AS entitySet,
       l.[bcCompanyId], MAX(l.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(l.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesReturnOrderLines] l
 WHERE l.[documentId] IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesReturnOrders] h
                    WHERE h.[bcCompanyId] = l.[bcCompanyId] AND h.[id] = l.[documentId])
 GROUP BY l.[bcCompanyId];
GO

DROP VIEW IF EXISTS [bcModel].[vw_dqEventsWithoutDocument];
GO
-- 12 entity set(s) checked.
CREATE VIEW [bcModel].[vw_dqEventsWithoutDocument] AS
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesQuotes' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Quote'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesQuotes] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Order'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesInvoices' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Invoice'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesInvoices] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesCreditMemos' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Credit Memo'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesCreditMemos] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesBlanketOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Blanket Order'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesBlanketOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('salesReturnOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Return Order'
   AND e.[eventType] IN ('salesDocumentDeleted', 'salesDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[salesReturnOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseQuotes' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Quote'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseQuotes] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Order'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseInvoices' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Invoice'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseInvoices] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseCreditMemos' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Credit Memo'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseCreditMemos] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseBlanketOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Blanket Order'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseBlanketOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId]
UNION ALL
SELECT CAST('eventWithoutDoc' AS varchar(16)) AS checkName,
       CAST('purchaseReturnOrders' AS varchar(100)) AS entitySet,
       e.[bcCompanyId], MAX(e.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(e.[id] AS varchar(36))) AS sampleId
  FROM [bc].[documentEvents] e
 WHERE e.[documentType] = 'Return Order'
   AND e.[eventType] IN ('purchaseDocumentDeleted', 'purchaseDocumentCancelled')
   AND NOT EXISTS (SELECT 1 FROM [bc].[purchaseReturnOrders] d
                    WHERE d.[bcCompanyId] = e.[bcCompanyId] AND (d.[id] = e.[documentId] OR d.[number] = e.[documentNumber]))
 GROUP BY e.[bcCompanyId];
GO

DROP VIEW IF EXISTS [bcModel].[vw_dqDuplicateKeys];
GO
-- 20 entity set(s) checked.
CREATE VIEW [bcModel].[vw_dqDuplicateKeys] AS
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('customers' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[customers] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('glAccounts' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[glAccounts] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('items' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[items] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('postedPurchaseCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseCreditMemos] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('postedPurchaseInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseInvoices] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('postedSalesCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesCreditMemos] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('postedSalesInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesInvoices] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseBlanketOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseBlanketOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseCreditMemos] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseInvoices] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseQuotes' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseQuotes] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('purchaseReturnOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseReturnOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesBlanketOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesBlanketOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesCreditMemos] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesInvoices] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesQuotes' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesQuotes] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('salesReturnOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[salesReturnOrders] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1
UNION ALL
SELECT CAST('duplicateKey' AS varchar(16)) AS checkName,
       CAST('vendors' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[number] AS varchar(36))) AS sampleId
  FROM [bc].[vendors] t
 WHERE t.[number] IS NOT NULL AND t.[number] <> ''
 GROUP BY t.[bcCompanyId], t.[number]
HAVING COUNT(DISTINCT t.[id]) > 1;
GO

DROP VIEW IF EXISTS [bcModel].[vw_dqDanglingDimSets];
GO
-- 37 entity set(s) checked.
CREATE VIEW [bcModel].[vw_dqDanglingDimSets] AS
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('custLedgerEntries' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[custLedgerEntries] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('generalLedgerEntries' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[generalLedgerEntries] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('itemLedgerEntries' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[itemLedgerEntries] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedPurchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseCreditMemoLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedPurchaseCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseCreditMemos] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedPurchaseInvoiceLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseInvoiceLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedPurchaseInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedPurchaseInvoices] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedSalesCreditMemoLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesCreditMemoLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedSalesCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesCreditMemos] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedSalesInvoiceLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesInvoiceLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('postedSalesInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[postedSalesInvoices] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseBlanketOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseBlanketOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseBlanketOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseBlanketOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseCreditMemoLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseCreditMemoLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseCreditMemos] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseInvoiceLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseInvoiceLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseInvoices] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseQuoteLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseQuoteLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseQuotes' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseQuotes] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseReturnOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseReturnOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('purchaseReturnOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[purchaseReturnOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesBlanketOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesBlanketOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesBlanketOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesBlanketOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesCreditMemoLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesCreditMemoLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesCreditMemos' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesCreditMemos] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesInvoiceLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesInvoiceLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesInvoices' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesInvoices] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesQuoteLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesQuoteLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesQuotes' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesQuotes] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesReturnOrderLines' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesReturnOrderLines] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('salesReturnOrders' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[salesReturnOrders] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('valueEntries' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[valueEntries] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId]
UNION ALL
SELECT CAST('danglingDimSet' AS varchar(16)) AS checkName,
       CAST('vendorLedgerEntries' AS varchar(100)) AS entitySet,
       t.[bcCompanyId], MAX(t.[bcCompanyName]) AS companyName,
       COUNT(*) AS failingRows, MIN(CAST(t.[id] AS varchar(36))) AS sampleId
  FROM [bc].[vendorLedgerEntries] t
 WHERE t.[dimensionSetId] IS NOT NULL AND t.[dimensionSetId] <> 0
   AND NOT EXISTS (SELECT 1 FROM [bc].[dimensionSetEntries] x
                    WHERE x.[bcCompanyId] = t.[bcCompanyId] AND x.[dimensionSetId] = t.[dimensionSetId])
 GROUP BY t.[bcCompanyId];
GO

DROP VIEW IF EXISTS [bcModel].[vw_dataQuality];
GO
CREATE VIEW [bcModel].[vw_dataQuality] AS
SELECT q.[checkName], q.[entitySet], q.[bcCompanyId], q.[companyName],
       q.[failingRows], q.[sampleId]
  FROM [bcModel].[vw_dqOrphanLines] q
UNION ALL
SELECT q.[checkName], q.[entitySet], q.[bcCompanyId], q.[companyName],
       q.[failingRows], q.[sampleId]
  FROM [bcModel].[vw_dqEventsWithoutDocument] q
UNION ALL
SELECT q.[checkName], q.[entitySet], q.[bcCompanyId], q.[companyName],
       q.[failingRows], q.[sampleId]
  FROM [bcModel].[vw_dqDuplicateKeys] q
UNION ALL
SELECT q.[checkName], q.[entitySet], q.[bcCompanyId], q.[companyName],
       q.[failingRows], q.[sampleId]
  FROM [bcModel].[vw_dqDanglingDimSets] q;
GO
